spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/moviedb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: amoir820
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

line:
  user:
    id: U0727eec495684a7762cd62f93b0c57cb
  channel:
    token: U9zlegJyS/D2gbiPKj2H1xOpm4ZiJ80izi8Dxb5ynEIwisTfFZkUEuE9MCfaoSmYL0/HyttFEveXKoW4fA3p0CaYwFWZusiv5pU4jR6s18v/diuzt8pxJlNGTw26piYK4NIBvr6jD1BSyawEytj9DgdB04t89/1O/w1cDnyilFU=
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace